# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-25 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170524_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Resume_Content',
        ),
        migrations.RenameModel(
            old_name='PDF',
            new_name='Resume_PDF',
        ),
    ]
