# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-30 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170524_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume_content',
            options={'verbose_name': 'Resume Content', 'verbose_name_plural': 'Resume Content'},
        ),
        migrations.AlterModelOptions(
            name='resume_pdf',
            options={'verbose_name': 'Resume PDF', 'verbose_name_plural': 'Resume PDF'},
        ),
    ]
