# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('D', 'Design'), ('B', 'Built')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='', help_text='Creates unique URL')),
                ('summary', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('date', models.CharField(default='', help_text='Free text date description', max_length=200)),
                ('order', models.PositiveIntegerField(default=500, help_text='Order displayed. 1-3 will be shown on main page')),
                ('hidden', models.BooleanField(default=True, help_text='If hidden, will only be visible with URL (no links)')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/images/')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('main_image', models.BooleanField(default=False, help_text='Will display on main page and top of detail page')),
                ('secondary_image', models.BooleanField(default=False, help_text='Will display as second image on detail page. All else part of slide show')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Categorie')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project_Detail')),
            ],
        ),
    ]
