# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-22 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_image',
            name='category',
        ),
        migrations.AddField(
            model_name='project_detail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Categorie'),
        ),
        migrations.AlterField(
            model_name='project_image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
