# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-24 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20160823_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='type',
        ),
        migrations.AddField(
            model_name='project_detail',
            name='type',
            field=models.CharField(choices=[('D', 'Design'), ('B', 'Built')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='project_image',
            name='order',
            field=models.PositiveIntegerField(default=500, help_text='Order displayed. 1 is main image'),
        ),
    ]
