# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160823_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project_image',
            name='type',
        ),
        migrations.AlterField(
            model_name='project_image',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project_Detail'),
        ),
    ]
