# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-25 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20160824_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project_Image'),
        ),
    ]
