# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-21 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20160828_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='project_detail',
            options={'verbose_name': 'Detail', 'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='project_image',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
    ]
