# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-30 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20170521_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_image',
            name='built_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project_image',
            name='design_main',
            field=models.BooleanField(default=False),
        ),
    ]
