# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-31 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170529_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_detail',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='hidden',
            field=models.BooleanField(default=True, help_text="Ignore this, I don't know why it's here"),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='order',
            field=models.PositiveIntegerField(default=500, help_text='Order displayed.'),
        ),
        migrations.AlterField(
            model_name='project_image',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project_Detail'),
        ),
    ]
